name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **This repository is not like any other repository. It does not create new releases; it only releases new files.**
        **Forget about scrolling the whole release page to find files. Just read the [README.md](../main/README.md) file and select the app you want to download.**
        **Change log** :point_down:
        [Morphe](https://github.com/MorpheApp/morphe-patches/releases/)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
        name: YouTube Morphe
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
